version: '3.7'
services:
  web:
    image: "nginx:1.15"
    depends_on:
      - echo-server
      - fpm
    environment:
      - PROJECT_ROOT
    volumes:
      - ../web/berlussimo.template:/etc/nginx/conf.d/berlussimo.template
      - ${PROJECT_ROOT}:${PROJECT_ROOT}
    networks:
      - backend
    ports:
      - 80:80
    command: /bin/sh -c "envsubst '$$PROJECT_ROOT' < /etc/nginx/conf.d/berlussimo.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  fpm:
    build:
      context: ../fpm
      dockerfile: Dockerfile-development
    depends_on:
      - db
      - redis
    user: ${PROJECT_USER}
    working_dir: ${PROJECT_ROOT}
    volumes:
      - ${PROJECT_ROOT}:${PROJECT_ROOT}
      - ${COMPOSER_CACHE}:/.composer/
      - ../fpm/zz-docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/zz-docker-php-ext-xdebug.ini
    networks:
      - backend
  worker:
    build:
      context: ../fpm
      dockerfile: Dockerfile-development
    depends_on:
      - db
      - redis
    user: ${PROJECT_USER}
    working_dir: ${PROJECT_ROOT}
    volumes:
      - ${PROJECT_ROOT}:${PROJECT_ROOT}
    networks:
      - backend
    command: ["php", "artisan", "queue:work", "--tries=3", "--timeout=600", "--env=production"]
  db:
    image: "mariadb:10.3"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      - backend
    ports:
      - 3306:3306
  redis:
    image: "redis:5.0-stretch"
    volumes:
      - "redis-data:/data"
    networks:
      - backend
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
  echo-server:
    build:
      context: ../..
      dockerfile: ./docker/echo-server/Dockerfile
    depends_on:
      - redis
    networks:
      - backend
networks:
  backend:
volumes:
  db-data:
  redis-data: